### PR TITLE
Bugs in BumpChart

### LINKED ISSUE #105: setting time breaks BumpChart y labels
### Expected Behavior
Setting the `.time( )` method should have little to no effect on simple Bump Charts.

### Current Behavior
Both sets of y-axis labels become hidden. It is probably an issue with the default `tickFormat` functions defined in the constructor.

### Steps to Reproduce (for bugs)
http://jsfiddle.net/4cbyf9o3/1/

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS High Sierra

### LINKED ISSUE #106: timeline does not work in BumpChart
### Expected Behavior
When changing the timeline, the x-axis should change to reflect the new data.

### Current Behavior
It seems like the value for the x-axis is currently being determined by the overall data, and not the `filteredData`.

### Steps to Reproduce (for bugs)
http://jsfiddle.net/4cbyf9o3/2/

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS High Sierra

### PR DESCRIPTION
**Pull request by cnavarreteliz**
### Description

closes #105 
The bug was caused because `xAxis` needed a special margin when `y2Exists` and `this._time` was true. 

To fix this bug, I set a `timeMargin` variable, that check if there is time dimension defined in `xAxis` or `x2Axis`.

closes #106 
The bug was caused because `domain` was not change when you updated timeline.

To fix this bug, I updated `(n)Domain` with new limits obtained from timeline. 

And also, I improved the comparison in `BumpChart.js`, because in javascript there is a bug comparing dates. [Explanation here](https://stackoverflow.com/questions/7244513/javascript-date-comparisons-dont-equal)

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

### CODE REVIEW

File: src/Plot.js [hunk 1]
```diff
@@ -570,12 +577,12 @@ export default class Plot extends Viz {
 
     const y2Transform = `translate(-${this._margin.right}, ${this._margin.top + topOffset})`;
     const y2Group = elem("g.d3plus-plot-y2-axis", {parent, transition, enter: {transform: y2Transform}, update: {transform: y2Transform}});
-
+    const timeMargin = (xTime || x2Time) && y2Exists ? y2TestRange[0] : 0;
```
Comment (davelandry) [inline src/Plot.js]: This solution does not work for all test cases, and is a band-aid over the real problem, which I believe is related to how the `xDifference` value is being calculated. Take a look at this example code, which does not use any secondary axes but breaks when using the `time` method:

```js
var data = [
    {id: "alpha", alphaX: 2004, alphaY:  7},
    {id: "alpha", alphaX: 2005, alphaY: 25},
    {id: "alpha", alphaX: 2006, alphaY: 13},
];

new d3plus.LinePlot()
  .data(data)
  .groupBy("id")
  .x("alphaX")
  .y("alphaY")
  .time("alphaX") // comment this line to see the difference
  .timeline(false)
  .render();
```

File: src/BumpChart.js [hunk 2]
```diff
@@ -60,7 +61,7 @@ export default class BumpChart extends Plot {
       tickFormat: val => {
         const data = this._formattedData;
         const xDomain = this._xDomain;
-        const endData = data.filter(d => d.x === xDomain[xDomain.length - 1]);
+        const endData = data.filter(d => this._time ? d.x.getTime() === xDomain[xDomain.length - 1].getTime() : d.x === xDomain[xDomain.length - 1]);
```
Comment (davelandry) [inline src/BumpChart.js]: instead of relying on `this._time` to be true (which may not always relate to the X-axis), let's do a more manual Date detection (and only convert the min and max values once, not in each loop of the filter). Something like this:

```js
const xDomain = this._xDomain;
const xMin = xDomain[0] instanceof Date ? xDomain[0].getTime() : xDomain[0];
const startData = data.filter(d => (d.x instanceof Date ? d.x.getTime() : d.x) === xMin);
```

File: src/Plot.js [hunk 3]
```diff
@@ -387,6 +387,14 @@ export default class Plot extends Viz {
...
     y2Domain = y2.domain();
 
+    const startTime = date(data[0].discrete);
+    const endTime = date(data[data.length - 1].discrete);
+
+    if (xTime) xDomain = [startTime, endTime];
+    if (x2Time) x2Domain = [startTime, endTime];
+    if (yTime) yDomain = [startTime, endTime];
+    if (y2Time) y2Domain = [startTime, endTime];
+
```
Comment (davelandry) [inline src/Plot.js]: these 6 lines aren't necessary. the domains are already parsed into times in the code above (`xDomain = xDomain.map(date);`)

File: src/Plot.js [hunk 4]
```diff
@@ -570,12 +576,12 @@ export default class Plot extends Viz {
 
     const y2Transform = `translate(-${this._margin.right}, ${this._margin.top + topOffset})`;
     const y2Group = elem("g.d3plus-plot-y2-axis", {parent, transition, enter: {transform: y2Transform}, update: {transform: y2Transform}});
-
+    const timeMargin = xTime || x2Time ? xOffset - this._xTest.padding() : 0;
```
Comment (davelandry) [inline src/Plot.js]: this logic needs to be part of the `xDifference` variable when it's defined, as it directly effects `this._padding`, which in turn effects the positioning of any legend beneath the axis (so that it is centered on the axis itself). @cnavarreteliz please investigate why this needs to be different for time axis, because it is still not clear to me why this works (even though it does work).

File: src/Plot.js (hunk 3 above)
Comment (cnavarreteliz) [reply src/Plot.js]: `xDomain = xDomain.map(date);` doesn't capture changes in Timeline, and Those lines reflect the new data, solving #106. 
pr

File: src/Plot.js (hunk 4 above)
Comment (cnavarreteliz) [reply src/Plot.js]: The only difference between Plot with/without `time()` is `.ticks(xTicks)`, where its value is `undefined` when `time()` is defined.

Comment (davelandry) [reply src/Plot.js]: great code condensing here @cnavarreteliz!

File: src/Plot.js (hunk 3 above)
Comment (davelandry) [reply src/Plot.js]: I dug into this more, and it's actually the line below (`this._xDomain = xDomain;`) that is causing the problem! `this._xDomain` should only every be used for a user-defined xDomain, and the reason the `.map(date)` isn't working is because it's using the previous xDomain!

You should be able to delete these six lines, AND the line below, and it should all start working. Please test and let me know if it doesn't.
