### PR TITLE
modifies sorting logic to check for discrete sort and use it if it exists

### LINKED ISSUE #93: respect xSort/ySort when sorting data by discrete value
### Expected Behavior
If the user supplies a specific sort function, use that when sorting the data.

### Current Behavior
Currently, if a custom sort is provided (like for strings), the custom sort is not used and lines draw really weird. I would start by looking at lines 186, 226, and 264 of `src/Plot.js`.

### Steps to Reproduce (for bugs)
https://jsfiddle.net/5hafqu6b/2/

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS High Sierra

### PR DESCRIPTION
**Pull request by nbond211**
(closes #93 )

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

### CODE REVIEW

File: src/Plot.js [hunk 1]
```diff
@@ -184,6 +184,7 @@ export default class Plot extends Viz {
         }, {});
 
       data = data.sort((a, b) => {
+        if (this[`_${this._discrete}Sort`]) return this[`_${this._discrete}Sort`](a, b);
```
Comment (davelandry) [inline src/Plot.js]: When calling the user's sort method, make sure to pass them their original data points: `(a.data, b.data)`

File: src/Plot.js [hunk 2]
```diff
@@ -223,7 +224,12 @@ export default class Plot extends Viz {
         }
       });
 
-      data.sort((a, b) => a[this._discrete] - b[this._discrete]);
+      if (this[`_${this._discrete}Sort`]) {
+        data.sort(this[`_${this._discrete}Sort`]);
```
Comment (davelandry) [inline src/Plot.js]: this won't work because it's not passing the user's data value

File: src/Plot.js [hunk 3]
```diff
@@ -261,7 +267,12 @@ export default class Plot extends Viz {
         .concat(this._confidence && this._confidence[0] ? data.map(d => d.lci)  : [])
         .concat(this._confidence && this._confidence[1] ? data.map(d => d.hci) : []);
 
-      data.sort((a, b) => a[this._discrete] - b[this._discrete]);
+      if (this[`_${this._discrete}Sort`]) {
+        data.sort(this[`_${this._discrete}Sort`]);
```
Comment (davelandry) [inline src/Plot.js]: same as above, this won't work without the user's original data
